#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;

my $dev = shift @ARGV;

$dev ||= 'eth0';

my $c = eval{ YAML::XS::LoadFile "$RealBin/../conf.yml"; };
die "load conf fail: $@" if $@;
die "net undef" unless $c->{net};

system "iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT";
system "iptables --append FORWARD --source $c->{net} --jump ACCEPT";
system "iptables -t nat -A POSTROUTING -s $c->{net} -o $dev -j MASQUERADE";
system "iptables-save";
system "sysctl -w net.ipv4.ip_forward=1";

#vi /etc/sysctl.conf --> net.ipv4.ip_forward=1 （永久开启）
