#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;

my $c = eval{ YAML::XS::LoadFile "$RealBin/../conf.yml"; };
die "load conf fail: $@" if $@;

my $port = $c->{supernode}{port};
die "port err" unless $port && $port =~ /^\d+$/;
system "supernode -p $port";

my $name = `cat $RealBin/../name`;
chomp $name;

my @x = `ifconfig |grep ^$c->{d}:`;
chomp @x;

if( @x )
{
    map{ print "$_\n" }@x;
    print "Already running, skip.\n";
    exit;
}
system "edge -d $c->{d} -a $c->{edge}{$name} -c $c->{c} -k $c->{k} -l $c->{supernode}{ip}:$port -M $c->{m} -r";
