#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;

my $c = eval{ YAML::XS::LoadFile "$RealBin/../conf.yml"; };
die "load conf fail: $@" if $@;

my @x = `ifconfig |grep ^$c->{d}:`;
chomp @x;

if( @x )
{
    print "running\n";
    exit;
}
else
{
    print "stoped.\n";
}
