#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;

my $c = eval{ YAML::XS::LoadFile "$RealBin/../conf.yml"; };
die "load conf fail: $@" if $@;

die "d undef" unless $c->{d};
my    @x = `ifconfig |grep ^$c->{d}:`;
chomp @x;

printf "%s\n", @x ? "running" : "stoped";
