#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

use FindBin qw( $RealBin );
use YAML::XS;

my $c = eval{ YAML::XS::LoadFile "$RealBin/../conf.yml"; };
die "load conf fail: $@" if $@;

my    $name = `cat $RealBin/../my.name`;
chomp $name;
die "name undef" unless $name;

map{ die "$_ undef" unless $c->{$_} }qw( d c k m );
map{ die "supernode.$_ undef" unless $c->{supernode}{$_} }qw( ip port );

system "ps -ef|grep ' $c->{supernode}{ip}:$c->{supernode}{port} '|grep ' $c->{edge}{$name} '|grep ' $c->{c} '|grep ' $c->{d} '|awk '{print \$2}'|xargs -i{} kill {}";
